#!/bin/bash
echo "Testing email card execution with fallback..."
echo ""
echo "This will test if the executor can:"
echo "1. Extract email from card description/rationale"
echo "2. Successfully send email via Resend"
echo "3. Move card to 'done' state"
echo ""
echo "Use the browser to:"
echo "1. Click on one of the 'Blocked' email cards"
echo "2. Click 'Approve' button"
echo "3. Click 'Send' button"
echo "4. Watch the server console for debug logs"
echo ""
echo "Expected logs:"
echo "- [Email Execution] Extracted email from card text: rod@myroihome.com"
echo "- [Email Execution] Recipient email resolved: { recipientEmail: 'rod@myroihome.com', source: 'payload' }"
echo "- Email sent successfully"
echo ""
