/**
 * Extract actionable tasks from research summaries and create kanban cards
 */

import { generateObject } from 'ai';
import { anthropic } from '@ai-sdk/anthropic';
import { z } from 'zod';

// Schema for extracted actions
const ExtractedActionSchema = z.object({
  title: z.string().describe('Short, actionable title for the task'),
  description: z.string().describe('Detailed description of what needs to be done'),
  type: z.enum(['send_email', 'schedule_call', 'create_task', 'research']).describe('Type of action'),
  priority: z.enum(['high', 'medium', 'low']).describe('Priority based on urgency'),
  timeframe: z.enum(['immediate', 'short_term', 'ongoing']).describe('When this should be done'),
  target_contact: z.string().optional().describe('Name of the person to contact, if applicable'),
  rationale: z.string().describe('Why this action is recommended'),
});

const ActionExtractionResultSchema = z.object({
  actions: z.array(ExtractedActionSchema),
});

export type ExtractedAction = z.infer<typeof ExtractedActionSchema>;

/**
 * Extract actionable tasks from a research summary using AI
 */
export async function extractActionsFromResearch(
  researchSummary: string,
  clientName: string,
  existingContacts: Array<{ name: string; email?: string; title?: string }>
): Promise<ExtractedAction[]> {
  const contactList = existingContacts.length > 0
    ? existingContacts.map(c => `- ${c.name}${c.title ? ` (${c.title})` : ''}${c.email ? ` - ${c.email}` : ''}`).join('\n')
    : 'No contacts on file.';

  const prompt = `You are a sales operations AI. Analyze this research summary for ${clientName} and extract specific, actionable next steps.

RESEARCH SUMMARY:
${researchSummary}

EXISTING CONTACTS:
${contactList}

TASK:
Extract 3-7 specific, actionable tasks from the research. Focus on:
1. Email outreach to specific people (if we have their email)
2. Phone calls to schedule
3. Data cleanup tasks (like fixing typos, updating records)
4. Follow-up research needed

RULES:
- Only create "send_email" actions if we have an email address for that contact
- Use "schedule_call" for phone outreach when no email is available
- Use "create_task" for internal tasks (data cleanup, preparation work)
- Prioritize based on timeframe mentioned (IMMEDIATE = high, SHORT-TERM = medium, ONGOING = low)
- Be specific - include names and what to say/do
- Skip vague recommendations like "monitor" or "track" - focus on concrete actions

Return actionable tasks that can be executed.`;

  try {
    const { object } = await generateObject({
      model: anthropic('claude-sonnet-4-5-20250929'),
      schema: ActionExtractionResultSchema,
      prompt,
      temperature: 0.3,
    });

    console.log(`[ActionExtractor] Extracted ${object.actions.length} actions from research`);
    return object.actions;
  } catch (error) {
    console.error('[ActionExtractor] Failed to extract actions:', error);
    return [];
  }
}

/**
 * Convert extracted actions to kanban card format
 */
export function actionsToCardPayloads(
  actions: ExtractedAction[],
  clientId: string,
  contacts: Array<{ id: string; firstName: string; lastName: string; email?: string }>
): Array<{
  type: string;
  title: string;
  description: string;
  rationale: string;
  priority: 'high' | 'medium' | 'low';
  client_id: string;
  contact_id?: string;
  action_payload?: any;
}> {
  return actions.map(action => {
    // Try to match target contact to existing contacts
    let contactId: string | undefined;
    let contactEmail: string | undefined;

    if (action.target_contact) {
      const targetLower = action.target_contact.toLowerCase();
      const matchedContact = contacts.find(c => {
        const fullName = `${c.firstName} ${c.lastName}`.toLowerCase();
        return fullName.includes(targetLower) || targetLower.includes(fullName) ||
               c.firstName.toLowerCase() === targetLower ||
               c.lastName.toLowerCase() === targetLower;
      });

      if (matchedContact) {
        contactId = matchedContact.id;
        contactEmail = matchedContact.email;
      }
    }

    const baseCard = {
      type: action.type,
      title: action.title,
      description: action.description,
      rationale: action.rationale,
      priority: action.priority,
      client_id: clientId,
      contact_id: contactId,
    };

    // Add action_payload based on type
    if (action.type === 'send_email' && contactEmail) {
      return {
        ...baseCard,
        action_payload: {
          to: contactEmail,
          subject: '', // Will be generated by email composer
          body: '', // Will be generated by email composer
          draft_context: action.description,
        },
      };
    }

    if (action.type === 'schedule_call') {
      return {
        ...baseCard,
        action_payload: {
          purpose: action.description,
          suggested_duration: 15,
        },
      };
    }

    return {
      ...baseCard,
      action_payload: {
        task_description: action.description,
      },
    };
  });
}

/**
 * Map timeframe to priority
 */
export function timeframeToPriority(timeframe: string): 'high' | 'medium' | 'low' {
  switch (timeframe) {
    case 'immediate':
      return 'high';
    case 'short_term':
      return 'medium';
    case 'ongoing':
    default:
      return 'low';
  }
}
